[package]
name = "forust"
version = "0.1.0"
authors = ["RegaladoEdgar <edgar.regalado18@tectijuana.edu.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotlib = "0.5.1"
